truebaseURL = "https://zeroone01.pages.dev"
languageCode = "fa"
defaultContentLanguage = "fa"
title = "ZeroOne"
theme = "PaperMod"

[pagination]
pagerSize = 8

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

publishDir = "public"

[params]
[[params.social]]
name = "twitter"
url = "https://twitter.com/..."

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "| صفر و یک |"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"
[[params.profileMode.buttons]]
name = "Posts"
url = "posts"
[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "سلام سینا حسینی هستم"
Content = """ برنامه چه نویسی :) """



[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com"

[[params.socialIcons]]
name = "telegram"
url = "https://telegram.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/sina-one"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/"

[params.analytics.google]
SiteVerificationTag = "XYZabc"
[params.analytics.bing]
SiteVerificationTag = "XYZabc"
[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/<path_to_repo>/content"
Text = "Suggest Changes"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

pygmentsUseClasses = true

[markup.highlight]
noClasses = false

[permalinks]
  posts = "/:year/:month/:title/"

[[menu.main]]
identifier = "FATags"
name = "تگ‌ها"
url = "/fatags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "آرشیو"
url = "/archives/"
weight = 30

[[menu.main]]
identifier = "about me"
name = "درباره من"
url = "/aboutme/"
weight = 30

[languages.fa]
languageName = "farsi"
weight = 1
languagedirection = "rtl"

[languages.fa.taxonomies]
category = "categories"
tag = "fatags"
series = "series"
